#!/usr/bin/env sh

## Dirty way to ensure the script is running in the correct folder
cd ~/dotfiles/usr

if [[ -z "$@" ]]; then
  sudo stow --dotfiles --no-folding -R -t /usr */
else
  sudo stow --dotfiles --no-folding -R -t /usr "$@"
fi
