import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window.dimensions]
columns=130
lines=35

[window]
opacity=0.95
blur=true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size=14
