#!/usr/bin/env sh

## Dirty way to ensure the script is running in the correct folder
cd ~/dotfiles/home

if [[ -z "$@" ]]; then
  stow --dotfiles --no-folding -R -t $HOME */
else
  stow --dotfiles --no-folding -R -t $HOME "$@"
fi
