[os]
disabled = false
format = " [$symbol](green) [$name]($style) "

[os.symbols]
Arch = '󰣇'
openSUSE = ' '

[directory]
truncation_length = 8

[username]
show_always = true
format = " [$user]($style) in "
