#!/usr/bin/env sh

## Dirty way to ensure the script is running in the correct folder
cd ~/dotfiles/etc

if [[ -z "$@" ]]; then
  sudo stow --dotfiles --no-folding -R -t /etc */
else
  sudo stow --dotfiles --no-folding -R -t /etc "$@"
fi
