[settings]
minimum_release_age = "0s"

[tools]
age = "latest"
fnox = "latest"
go = "latest"
node = "latest"
opencode = "latest"
pipx = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
typst = "latest"
usage = "latest"
